apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: info@webered.com
    privateKeySecretRef:
      name: staging
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          cloudflare:
            email: weberedok@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "dev.nexar.com.ar"